package com.example.justbintime.data

import android.content.Context
import android.util.Log
import androidx.room.Database
import androidx.room.Room
import androidx.room.RoomDatabase
import androidx.room.TypeConverters
import androidx.sqlite.db.SupportSQLiteDatabase
import com.example.justbintime.data.dao.BinDao
import com.example.justbintime.data.dao.ColourDao
import com.example.justbintime.data.`object`.Bin
import com.example.justbintime.data.`object`.BinColours
import com.example.justbintime.ui.theme.BinGardenColor
import com.example.justbintime.ui.theme.BinLandfillColor
import com.example.justbintime.ui.theme.BinRecyclingColor
import java.util.concurrent.Executors


@Database(entities = [Bin::class, BinColours::class], version = 8, exportSchema = true)
@TypeConverters(Converters::class)
abstract class AppDatabase : RoomDatabase() {
    abstract fun binDao(): BinDao
    abstract fun colourDao(): ColourDao

    companion object {
        @Volatile
        private var INSTANCE: AppDatabase? = null

        fun getDatabase(context: Context): AppDatabase {
            return INSTANCE ?: synchronized(this) {
                val inst = Room.databaseBuilder(
                    context.applicationContext,
                    AppDatabase::class.java, "bin_database"
                ).fallbackToDestructiveMigration()
                    .addCallback(object : Callback() {
                    override fun onCreate(db: SupportSQLiteDatabase) {
                        super.onCreate(db)
                        Executors.newSingleThreadExecutor().execute {
                            INSTANCE?.let {
                                initDatabase(it)
                            }
                        }
                    }
                    override fun onDestructiveMigration(db: SupportSQLiteDatabase) {
                        super.onDestructiveMigration(db)
                        Executors.newSingleThreadExecutor().execute {
                            INSTANCE?.let {
                                initDatabase(it)
                            }
                        }
                    }
                })
                .build()
                INSTANCE = inst
                inst
            }
        }

        fun initDatabase(instance: AppDatabase) {
            val bindao = instance.binDao()
            val coldao = instance.colourDao()
            bindao.deleteAll()
            coldao.deleteAll()
            val bfact = BinFactory()

            // First, add the BinColours, so we can fetch their bcId (autogenerated)
            val landfillColor = BinColours(BinLandfillColor)
            val recyclingColor = BinColours(BinRecyclingColor)
            val gardenColor = BinColours(BinGardenColor)
            coldao.upsert(landfillColor, recyclingColor, gardenColor)

            val numCols = coldao.getAll().size
            Log.e("AppDatabase", "Prepop'd $numCols colours")

            // Then, make bins with a reference to the BinColours ids
            val landfillBin = bfact.makeLandfillBinWithColours().bin
            landfillBin.binColoursId = coldao.getByPrimary(landfillColor.cPrimary).first().bcId
            val recyclingBin = bfact.makeRecyclingBinWithColours().bin
            recyclingBin.binColoursId = coldao.getByPrimary(recyclingColor.cPrimary).first().bcId
            val gardenBin = bfact.makeRecyclingBinWithColours().bin
            gardenBin.binColoursId = coldao.getByPrimary(gardenColor.cPrimary).first().bcId
            bindao.insertAll(landfillBin, recyclingBin, gardenBin)

            val numBins = bindao.getAll().size
            Log.e("AppDatabase", "Prepop'd $numBins bins")
        }
    }

}
